apiVersion: v1
kind: Pod
metadata:
    name: stress
spec:
    containers:
    - image: prawien/stress
      imagePullPolicy: Always
      name: stress
      command: ["sleep","200"]
      resources:
        requests: 
          cpu: "200m" # 1 cpu = 1000m 
          memory: "250Mi"
        limits: 
          cpu: "300m"
          memory: "400Mi"