apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  labels:        # these labels are related to replicaset resource
    app: nginx
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:  # this is the syntax replicaset uses to find which pod should be maintained and scalled
      tier: frontend
  template:   # pod template labels are related to pod
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx
